---
#- name: install python-mysqldb
#  apt:
#    name: python-mysqldb
#    state: present
#    update_cache: yes
#  tags: python_mysql_connector

#check if mysql service is started
- name: Start the MySQL service
  service: 
    name: mysql 
    state: started
    enabled: true
  tags: mysql_status

#create Database
- name: Create Database
  mysql_db:
    name: "{{ db_name }}"
    state: present
  tags: create_db

- name: Add user
  mysql_user:
    name: "{{ username }}"
    host: "{{ host }}"
    password: "{{ password }}"
    priv: ' {{ db_name }}.*:ALL' 
    state: present
  tags: add_user

- name: Delete user
  mysql_user:
    name: "{{ username }}"
    state: absent
  tags: delete_user

- name: Delete Database
  mysql_db:
    name: " {{ db_name }}"
    state: absent
  tags: remove_db

- name: import database
  mysql_db:
    login_user: "{{ username }}"
    login_password: "{{ password }}"
    name: "{{ db_name }}"
    state: import
    target: "/{{ deploy_dir }}/mockup_db.sql"
  tags: import_db
