---
# tasks file for user-management

## This Tasks Creates a Several Users on the Targeted Machine
- name:  Add Deployment User
  user:
    name: "{{ deploy_user }}"
    state: present
#    update_password: always
    password: "{{ default_user_password | password_hash('sha512','aes512') }}"
    shell: /bin/bash
    update_password: on_create
  tags: add_new_user

## This Task Creates SSH Public Key for Specified user
- name: Generate SSH Keys
  user:
    name: "{{ deploy_user }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
  tags: generate_ssh_keys

## This Task is to copy the public keys to user_account
- name: Update Authorized Keys for a User
  authorized_key:
    user: "{{ deploy_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tags: copy_pub_key

- name: Creates directory
  file:
    path: "{{ deploy_dir }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: 0755
  tags: create_dir

- name: Copy Deployment Necessary File
  copy:
    src: "{{ item }}"
    dest: "{{ deploy_dir }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
  with_items: 
    - '/tmp/test-1.0-SNAPSHOT-jar-with-dependencies.jar'
    - './etc'
    - './mockup_db.sql'
  tags: copy_deploy_file


- name: Deploy Jar File
  shell: cd {{ deploy_dir }} && java -jar {{ deploy_dir }}/test-1.0-SNAPSHOT-jar-with-dependencies.jar &
  tags: deploy_jar

## This task is to delete the user
- name: Delete Deploy Users
  user:
    name: "{{ deploy_user }}"
    state: absent
    remove: yes
  tags: remove_user
